### ISSUE TITLE
和wokerman相比有什么优势吗

### ISSUE THREAD

**Issue by zeke2024** [lixuancn/MeepoPS#1]
简单看了下代码，也是基于pcntl和libevent的机制的，感觉不到有什么特色呢

**Comment by lixuancn** [comment]
1、php的多进程就只有pcntl。自带的Select肯定没法和Libevent比。只要是PHP原生这类软件的都会有这些东西。

2、Workerman是前辈了，从公司自用到开源，这期间也参考了swool，Workerman。

3、优势的话，性能没有对比过，但是代码结构会更加优雅

**Comment by zeke2024** [comment]
嗯，多谢～
