### ISSUE TITLE
websocket和HTTP的API接口全部报错,

### ISSUE THREAD

**Issue by LiHaoLi** [lixuancn/MeepoPS#10]
[root@VM_40_223_centos meepops]# sudo php demo-websocket.php start

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /www/wwwroot/meepops/demo-websocket.php on line 16

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /www/wwwroot/meepops/demo-websocket.php on line 16

Parse error: syntax error, unexpected T_STRING in /www/wwwroot/meepops/demo-websocket.php on line 16
[root@VM_40_223_centos meepops]# sudo php demo-http.php start

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /www/wwwroot/meepops/demo-http.php on line 17

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /www/wwwroot/meepops/demo-http.php on line 17

Parse error: syntax error, unexpected T_STRING in /www/wwwroot/meepops/demo-http.php on line 17

**Comment by lixuancn** [comment]
这。。。你PHP用的5.2或者更低的版本吧

**Comment by iMactool** [comment]
在启动入口那里直接判断PHP版本，低于指定版本直接不给他启动~

**Comment by lixuancn** [comment]
恩，启动那里我现在给加一个。

**Comment by LiHaoLi** [comment]
用的是PHP5.6

**Comment by LiHaoLi** [comment]
Linux是7.2x64

**Comment by lixuancn** [comment]
这东西你就检查你是不是改过demo-websocket.php和demo-http.php，改完是不是少了分号啊什么的。
