### ISSUE TITLE
降级回centOS6.5正常,centOS7.0报错,/解析错误,请作者考虑兼容做个排查,谢谢

### ISSUE THREAD

**Issue by LiHaoLi** [lixuancn/MeepoPS#12]
降级回centOS6.5正常,centOS7.0报错,/解析错误,请作者考虑兼容做个排查,谢谢

**Comment by lixuancn** [comment]
什么错误提示？我的博客就是在7上跑的

**Comment by XiangXuefeng** [comment]
PHP 7.1.5 
sudo  php demo-telnet.php start 错误如下：
PHP Fatal error:  Redefinition of parameter $_null in /data/www/MeepoPS/MeepoPS/Core/Event/Libevent.php on line 155
[INFO][2017-06-14 16:29:38][8889]MeepoPS check shutdown reason
[ERROR][2017-06-14 16:29:38][8889]stream_socket_serverMeepoPS unexpectedly quits. last error: {"type":64,"message":"Redefinition of parameter $_null","file":"\/data\/www\/MeepoPS\/MeepoPS\/Core\/Event\/Libevent.php","line":155}
[ERROR][2017-06-14 16:29:38][8888]MeepoPS instance(MeepoPS-Telnet:8889) exit. Status: 65280
PHP Fatal error:  Redefinition of parameter $_null in /data/www/MeepoPS/MeepoPS/Core/Event/Libevent.php on line 155

**Comment by lixuancn** [comment]
MeepoPS/Core/Event/Libevent.php  155行，public function timerCallback($_null1, $_null2, $timerId)的前两个参数原本都是$_null, 改成一个$_null1, 一个$_null2

**Comment by XiangXuefeng** [comment]
Fatal error: Cannot unset $this in MeepoPS/MeepoPS/Core/TransportProtocol/Tcp.php on line 353 ， 用dev的版本也不行。

**Comment by lixuancn** [comment]
是有这个问题，有同学反映过，但是我一直没有复现过，你可以把Tcp.php中的353行的unset($this);给删了，没有太大的影响。
