### ISSUE TITLE
为什么不传到composer上呢？

### ISSUE THREAD

**Issue by guandaxia** [lixuancn/MeepoPS#5]
我看文档目前是通过下载源代码，引入index.php的方式来操作的。为什么不传到composer上呢，通过composer来安装使用呢？

**Comment by lixuancn** [comment]
为了更通用，降低上手难度。到时候又要有很多人来问我composer怎么用=。=

**Comment by slince** [comment]
@lixuancn   真没必要，composer的普适性必然是要推广的；现在不做这个支持等于纵容

**Comment by lixuancn** [comment]
刚又看了一遍issue，composer的话也需要require 'vendor/autoload.php';  不用composer也需要require index.php，在引入的这一点上，有没有也啥区别吧

**Comment by guandaxia** [comment]
composer 使用起来比较方便，一个命令就可以集成到项目中来，更新的时候也可以通过命令来更新，而不是手动去下载源码替换。composer毕竟还是个趋势，不会用的用户可以不考虑他们。

**Comment by lixuancn** [comment]
@guandaxia   @slince  感谢二位，好像说的很有道理，忙完手头的事情我就放到packagist。

此Issue已Close。3ks
