### ISSUE TITLE
关于 Libevent和Select 自动选择问题(PHP多版本环境引起)【已解决】

### ISSUE THREAD

**Issue by iMactool** [lixuancn/MeepoPS#9]
起因是我发现我明明安装了 Libevent ，但是 启动MeepoPS的时候却没有，发现cli下的php是系统自带的（我用vagrant+box）

接着看手册里的配置信息默认配置是 Select 轮询机制. 
[event] 这个节段里配置的，但是没有配置 Libevent 
再看源码的时候发现了：MeepoPS 自动选择优先会使用 [Libevent](https://github.com/lixuancn/MeepoPS/blob/34d0d11f9c7e6c6cea34f463698c4bea0a9989ab/MeepoPS/Core/MeepoPS.php#L574) 

那么问题就简单了，比如我的环境下
系统自带的php在 `/usr/bin/php` 下，安装的在 `/usr/local/php56/bin/php`下

解决方案 三步骤走起
```
sudo cp /usr/bin/php /usr/bin/php55
sudo rm /usr/bin/php
sudo ln -s /usr/local/php56/bin/php /usr/bin/php

```

再启动MeepoPS 就可以看到`Event: Libevent`了

```
MeepoPS Start:                         [OK]
-------------------------- MeepoPS Start Success ------------------------
MeepoPS Version: 0.0.5 | PHP Version: 5.6.29 | Master Pid: 14450 | Event: Libevent
```

这点官方文档个人觉得应该加个 notice 吧 ，由于没有就当是一个新的Issues吧 :)

**Comment by lixuancn** [comment]
我觉得这完全不是Issues吧。你的libevent装在了 /usr/local/php56/bin/php   而你在启动程序的时候用的是 /usr/bin/php。 /usr/bin/php是系统自带的PHP，该PHP并没有安装libevent，那么当然是启动select了。

如果你/usr/local/php56/bin/php meepops.php start 就没有问题了

**Comment by iMactool** [comment]
嗯，是的。 
如果是绝对路径那啥问题都木有的

**Comment by lixuancn** [comment]
恩，启动那里我现在给加一个。
